name: MAIN

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy the project to the server
    runs-on: ubuntu-latest
    steps:
      - name: Restart
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd projects/GetIdBot

            git pull

            docker build \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --cache-from get-id-bot \
              -t get-id-bot .
            
            docker stop get-id-bot || true
            docker rm get-id-bot || true

            docker run -d \
              --network network \
              --restart always \
              --name get-id-bot \
              --env-file .env \
              get-id-bot
        
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}